/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Bus.DadosBO;
import Conexão.ContaDAO;
import Conexão.TransacaoDAO;
import Entidades.Conta;
import Entidades.Transacao;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Transferencia
     */
    public Transferencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btDeposito = new javax.swing.JButton();
        labelConta = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btVoltar1 = new javax.swing.JButton();
        btDeposito1 = new javax.swing.JButton();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo2.png"))); // NOI18N

        btVoltar.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btDeposito.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deposito2.png"))); // NOI18N
        btDeposito.setText("Depositar");
        btDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDepositoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelConta.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        labelConta.setText("Conta");

        txtConta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContaKeyReleased(evt);
            }
        });

        labelValor.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        labelValor.setText("Valor");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo2.png"))); // NOI18N

        btVoltar1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btVoltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btVoltar1.setText("Voltar");
        btVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltar1ActionPerformed(evt);
            }
        });

        btDeposito1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        btDeposito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/transacao.png"))); // NOI18N
        btDeposito1.setText("Transferir");
        btDeposito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeposito1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelConta)
                            .addComponent(labelValor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btVoltar1)
                        .addGap(59, 59, 59)
                        .addComponent(btDeposito1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDeposito1)
                    .addComponent(btVoltar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtContaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContaKeyReleased
        txtConta.setText(txtConta.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_txtContaKeyReleased

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        txtValor.setText(txtValor.getText().replaceAll("[^0-9|^]", ""));
    }//GEN-LAST:event_txtValorKeyReleased

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        TelaPrincipal screen = new TelaPrincipal();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDepositoActionPerformed
        
    }//GEN-LAST:event_btDepositoActionPerformed

    private void btVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltar1ActionPerformed
        TelaPrincipal screen = new TelaPrincipal();
        screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltar1ActionPerformed

    private void btDeposito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeposito1ActionPerformed
        try{
            DadosBO.validandoDeposito(txtConta.getText(), txtValor.getText());
            int numero = Integer.parseInt(txtConta.getText());
        int valor = Integer.parseInt(txtValor.getText());
        Conta conta = ContaDAO.retornaConta(numero);
        int t = Login.lconta.transferir(valor, conta);
        if(conta!=null){
            if (t==1){
                ContaDAO.updateSaldo(Login.lconta);
                ContaDAO.updateSaldo(conta);
                Transacao tr = new Transacao("+",valor,"Transferência",numero);
                TransacaoDAO.inserirBanco(tr,Login.lconta);
                Transacao tra = new Transacao("-",valor,"Transferência",Login.lconta.getNumeroConta());
                TransacaoDAO.inserirBanco(tra,Login.lconta);
                 JOptionPane.showMessageDialog(null, "Transferência feita com sucesso");
            }
            else if(t==2){
                JOptionPane.showMessageDialog(null, "Nao pode transferir para sua própria conta");
            }
            else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Conta não encontrada");
        }
         txtConta.setText("");
         txtValor.setText("");
            
        }catch(RuntimeException e){
            JOptionPane.showMessageDialog(this,e.getMessage(),"ATENÇÃO",JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_btDeposito1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDeposito;
    private javax.swing.JButton btDeposito1;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btVoltar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelConta;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTextField txtConta;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
